### PR TITLE
Update cloudevents sdk version to 4.0.2

### PR DESCRIPTION
**Pull request by sangeetha5491**
## Description

Fixes issue: https://github.com/adobe/generator-aio-app/issues/143

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by sgera — COMMENTED** [review]
Changes look good -

1. Just wondering why we didn’t move to the latest v4.0.3?
2. I am not able to recall - do we have automated integration tests or do we test the SDK’s interaction with EventsIngress manually?

**Comment by sangeetha5491** [comment]
@sgera As per this, it mentions the latest is 4.0.2: https://www.npmjs.com/package/cloudevents

**Comment by sandeep-paliwal** [comment]
@sangeetha5491 Changes look good. Can you confirm that the generated actions post these changes work as expected?

**Comment by sangeetha5491** [comment]
@sandeep-paliwal Yes it works as expected. Also now, it no longer shows the Server side request forgery vulnerability.

`=== npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @adobe/aio-sdk                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @adobe/aio-sdk > @adobe/aio-lib-audience-manager-cd >        │
│               │ swagger-client > cross-fetch > node-fetch                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1556                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @adobe/aio-sdk                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @adobe/aio-sdk > @adobe/aio-lib-campaign-standard >          │
│               │ swagger-client > cross-fetch > node-fetch                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1556                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @adobe/aio-sdk                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @adobe/aio-sdk > @adobe/aio-lib-customer-profile >           │
│               │ swagger-client > cross-fetch > node-fetch                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1556                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @openwhisk/wskdebug [dev]                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @openwhisk/wskdebug > isomorphic-fetch > node-fetch          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1556                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 4 low severity vulnerabilities in 1087 scanned packages
  4 vulnerabilities require manual review. See the full report for details.
`

**Review by sgera — APPROVED** [review]

**Review by shazron — APPROVED** [review]

**Comment by shazron** [comment]
The `aio-e2e-tests` repo runs a daily job that tests the master branch of several aio-libs. However, the e2e tests of aio-lib-events do not test with the `cloudevents` package specifically so there will be no change there.

**Review by sandeep-paliwal — APPROVED** [review]

**Pull request merged**
