### PR TITLE
Run eslint after test

### PR DESCRIPTION
**Pull request by tmathern**
Run eslint last.

## Description
When running eslint after the test, it's a bit friendlier when you are debugging (and run only given tests with .only).
So you always see test results.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
We run eslint first so it fails fast in the CI, so as not to waste running the tests twice.

**Comment by tmathern** [comment]
Maybe offer another option in package json, like running only unit tests then?

**Comment by tmathern** [comment]
I'm suggesting those changes because I'd like not to have to install jest globally (and without it installed globally, I can't run only unit tests by only running `jest`).

**Comment by tmathern** [comment]
@shazron Since you approved, will you merge it? I can't, I don't have write access.

**Pull request merged**
