### PR TITLE
Fixed file overwrite confirmation when new action is added 

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
We will merge manifest.yml changes instead of asking user confirmation to overwrite manifest.yml when new actions are added to aio app 

Replaced yeoman Generator.fs.write call with fs.writeFileSync which allows file overwrite
Related to - [https://github.com/adobe/aio-cli-plugin-app/issues/262](https://github.com/adobe/aio-cli-plugin-app/issues/262)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by purplecabbage — CHANGES_REQUESTED** [review]
Testing this, I think it was already fixed somewhere else.
The issue was specific to adding multiple actions at once, like on `app init`
This implementation completely side-steps and even hides the issue by writing to the filesystem directly.

**Comment by purplecabbage** [comment]
I think this and the issue can be closed.

**Comment by sandeep-paliwal** [comment]
> I think this and the issue can be closed.

There is still issue when we use `aio app add action` with multiple actions selected. So we would still need the change for those cases.

**Comment by purplecabbage** [comment]
> > I think this and the issue can be closed.
> 
> There is still issue when we use `aio app add action` with multiple actions selected. So we would still need the change for those cases.

I have verified that installing multiple actions results in only 1 merge question which is relevant in this case.
The issue was specific to app creation, where when we created a new app the user was faced with a decision about allowing the modification of files they had never even seen before ...
Once the app has been created, we have to assume that the user might have modified manifest.yml, so the merge/overwrite question IS valid.

**Comment by purplecabbage** [comment]
Test the following case:
- add a new action manually to manifest.yml (newAction)
- run aio app add action and choose 'newAction' as a name

**Comment by shazron** [comment]
@sandeep-paliwal is this still valid, since it's been 7 months, and it probably has to change with the new Ext Reg changes.

**Comment by sandeep-paliwal** [comment]
I think we had decided not to go ahead with the fix as issue didnt repro as previously reported. Closing this one

**Pull request closed without merging**
